title: "Sampada Chavan — Data Analyst Portfolio 4+ Years)"
description: "4+ years (5 overall) across healthcare, supply chain, and finance. Python • SQL • Power BI • Tableau • AWS/Azure."
theme: jekyll-theme-cayman
github_username: chavan1996

plugins:
  - jekyll-seo-tag

author:
  name: "Sampada Chavan"
  email: "sampada1996@gmail.com"          
  linkedin: "https://www.linkedin.com/in/sampadachavan18/" 
